## numpy向量说明
不要用秩为1的数组：`a = np.random.randn(5)`

### 建议的用法
```
a = np.random.randn(5,1) # column vector
b = np.random.randn(1,5) # raw vector
```

In [4]:
import numpy as np
a = np.random.randn(5)

In [5]:
print(a)


[-0.12460331 -0.1942213   1.47433623 -1.02178108  0.19000811]


In [6]:
print(a.shape)

(5,)


In [7]:
print(a.T)

[-0.12460331 -0.1942213   1.47433623 -1.02178108  0.19000811]


In [10]:
print(np.dot(a,a.T))

3.3070548606758297


In [11]:
print(np.dot(a.T,a))

3.3070548606758297


In [12]:
a = np.random.randn(5,1)

In [13]:
print(a)

[[ 0.93108595]
 [-1.67743407]
 [-0.11033981]
 [ 0.19017228]
 [ 0.34658135]]


In [14]:
print(a.T)

[[ 0.93108595 -1.67743407 -0.11033981  0.19017228  0.34658135]]


In [17]:
print(np.dot(a,a.T))

[[ 0.86692105 -1.56183529 -0.10273585  0.17706673  0.32269703]
 [-1.56183529  2.81378505  0.18508776 -0.31900146 -0.58136737]
 [-0.10273585  0.18508776  0.01217487 -0.02098357 -0.03824172]
 [ 0.17706673 -0.31900146 -0.02098357  0.03616549  0.06591016]
 [ 0.32269703 -0.58136737 -0.03824172  0.06591016  0.12011863]]
